default: &mysql
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  username: admin
  password: 85cd284d

development:
  <<: *mysql
  database: team_dashboard_development

test:
  <<: *mysql
  database: team_dashboard_test

production:
  <<: *mysql
  database: team_dashboard_production
